Repository gabdiniz/soulpet-back, pull requests merged in 2023-05, with the labels that each got.

#60 Criar recurso PUT para atualização de Agendamentos
  index.js
  routes/agendamentos.js
Labels: documentation, enhancement

#61 Criar esquemas de validação do corpo da requisição
  database/agendamento.js
  database/cliente.js
  database/endereco.js
  database/pedido.js
  database/pet.js
  database/produto.js
  database/servico.js
  joi/customMessages.js
  package-lock.json
  package.json
  routes/agendamentos.js
  routes/clientes.js
  routes/pedidos.js
  routes/pets.js
  routes/produtos.js
  routes/servicos.js
Labels: documentation, enhancement

#62 Criar recurso PUT para atualização de Pedidos
  routes/pedidos.js
Labels: documentation, enhancement

#65 Crianção de esquema de logs com o mongoDB
  index.js
  log.js
  package-lock.json
  package.json
Labels: documentation, enhancement

#67 Get agendamento por id
  routes/agendamentos.js
Labels: documentation, enhancement

#68 Bug em get agendamentos por id
  routes/agendamentos.js
Labels: bug

#69 [SPT-9] Implementar uma tela de Dashboard do Sistema
  index.js
  package-lock.json
  routes/dashboard.js
Labels: documentation, enhancement

#70 Adicionar preenchiemento automático de uuid em pedidos
  database/pedido.js
Labels: enhancement

#71 Criar implementação de mensagem de erro de resposta
  index.js
  routes/agendamentos.js
  routes/clientes.js
  routes/dashboard.js
  routes/pedidos.js
  routes/pets.js
  routes/produtos.js
  routes/servicos.js
  utils/ErrorHandler.js
Labels: documentation, enhancement

#72 arquivo de trigger de backup do delete no MYSQL
  MySQL/soulpet.sql
Labels: documentation, enhancement
