Repository gabdiniz/soulpet-back, pull requests merged in 2023-04, with the labels that each got.

#29 Criar model de Produto
  database/produto.js
Labels: documentation, enhancement

#31 criação do model serviços
  database/servico.js
Labels: documentation, enhancement

#32 Implementação do get produtos
  routes/produtos.js
Labels: documentation, enhancement

#36 Consertar erros produto
  database/produto.js
  database/servico.js
  index.js
  routes/produtos.js
Labels: documentation, enhancement

#35 Criação do recurso GET para listagem de pedidos
  routes/pedidos.js
Labels: documentation

#37 Funcionalidade do delete de produto
  routes/produtos.js
Labels: documentation, enhancement

#38 criação do model Agendamento
  database/agendamento.js
Labels: documentation, enhancement

#39 Funcionalidade do get de agendamento
  database/agendamento.js
  routes/agendamento.js
Labels: documentation, enhancement

#40 Criar recurso POST para inserção de Serviços
  index.js
  routes/servicos.js
Labels: documentation, enhancement

#41 Remoção de produtos
  routes/pedidos.js
Labels: documentation

#42 [BE-10] Criar recurso GET para listagem de Serviços #10
  routes/servicos.js
Labels: documentation, enhancement

#43 criação da rota de inserção de agendamento
  database/agendamento.js
  index.js
  routes/agendamento.js
  routes/agendamentos.js
Labels: documentation, enhancement

#44 Funcionalidade de delete no agendamento
  routes/agendamentos.js
Labels: documentation, enhancement

#46 Rota delete de serviços
  routes/servicos.js
Labels: documentation, enhancement

#48 Crie uma rota POST para inserir múltiplos pedidos.
  index.js
  routes/pedidos.js
Labels: documentation

#45 criação da rota para editar serviços
  routes/pedidos.js
  routes/servicos.js
Labels: documentation, enhancement

#49 [BE-7] Criar recurso GET para mostrar apenas o Endereço dos Clientes#7
  routes/clientes.js
Labels: documentation, enhancement

#52 Reparar erro Model agendamentos
  database/agendamento.js
  routes/agendamentos.js
Labels: bug

#53 [BE-6] Criar recurso GET para listar os pets dos Clientes #6
  routes/clientes.js
Labels: documentation, enhancement

#54 Criação da rota PUT Produto
  routes/produtos.js
Labels: documentation, enhancement

#56 Consertar o post Produto
  routes/produtos.js
Labels: bug

#59 Fix produtos.js
  routes/produtos.js
Labels: bug
